name: build client zip

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: trygoda-client
          path: ./client
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: client.zip
