name: build client zip

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: trygoda-client-${{ steps.date.outputs.date }}
          path: ./client
